# -*- coding: utf-8 -*-
"""Webscraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13-Yyp-TbgEN-9aL0x0QJHfysJso6ehPU
"""

from googlesearch import search
print("Googlesearch package installed successfully!")

# set query to search for in Google
query = input("Enter query: ")
# execute query and store search results
results = search(query, tld="com", lang="en", stop=int(input("Enter no. of links reqd.: ")), pause=2)
# results2 = results
# iterate over all search results and print them
# for result in results:
#     print(result)

import requests
from bs4 import BeautifulSoup

# Send an HTTP request to the URL of the webpage you want to access
for result in results:
    response = requests.get(result)

    # Parse the HTML content using BeautifulSoup
    soup = BeautifulSoup(response.content, "html.parser")

    # Extract the text content of the webpage
    text = soup.get_text()

    print(text)
    print("\n_________________________________________________________________________________________________________________\n")

type(results)